// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: services/metadata/api/src/object.proto

package api

import (
	api "github.com/h-varmazyar/arvanStorage/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"id"`
	// @inject_tag: json:"key"
	Key string `protobuf:"bytes,2,opt,name=Key,proto3" json:"key"`
	// @inject_tag: json:"user_id"
	UserID string `protobuf:"bytes,3,opt,name=UserID,proto3" json:"user_id"`
	// @inject_tag: json:checksum"
	Checksum string `protobuf:"bytes,4,opt,name=Checksum,proto3" json:"Checksum,omitempty"`
	// @inject_tag: json:"size"
	Size int64 `protobuf:"varint,5,opt,name=Size,proto3" json:"size"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Object) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Object) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Object) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *Object) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Objects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:elements"
	Elements []*Object `protobuf:"bytes,1,rep,name=Elements,proto3" json:"Elements,omitempty"`
}

func (x *Objects) Reset() {
	*x = Objects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Objects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objects) ProtoMessage() {}

func (x *Objects) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objects.ProtoReflect.Descriptor instead.
func (*Objects) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{1}
}

func (x *Objects) GetElements() []*Object {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ObjectListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ObjectListReq) Reset() {
	*x = ObjectListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectListReq) ProtoMessage() {}

func (x *ObjectListReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectListReq.ProtoReflect.Descriptor instead.
func (*ObjectListReq) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{2}
}

type ObjectReturnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ObjectReturnReq) Reset() {
	*x = ObjectReturnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectReturnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReturnReq) ProtoMessage() {}

func (x *ObjectReturnReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReturnReq.ProtoReflect.Descriptor instead.
func (*ObjectReturnReq) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{3}
}

type ObjectDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ObjectDeleteReq) Reset() {
	*x = ObjectDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectDeleteReq) ProtoMessage() {}

func (x *ObjectDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectDeleteReq.ProtoReflect.Descriptor instead.
func (*ObjectDeleteReq) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{4}
}

type ObjectNewUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"key"
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"key"`
	// @inject_tag: json:"user_id"
	UserID string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"user_id"`
}

func (x *ObjectNewUploadReq) Reset() {
	*x = ObjectNewUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectNewUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectNewUploadReq) ProtoMessage() {}

func (x *ObjectNewUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectNewUploadReq.ProtoReflect.Descriptor instead.
func (*ObjectNewUploadReq) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectNewUploadReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectNewUploadReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type ObjectNewUploadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"upload_id"
	UploadID string `protobuf:"bytes,1,opt,name=UploadID,proto3" json:"upload_id"`
}

func (x *ObjectNewUploadResp) Reset() {
	*x = ObjectNewUploadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectNewUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectNewUploadResp) ProtoMessage() {}

func (x *ObjectNewUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectNewUploadResp.ProtoReflect.Descriptor instead.
func (*ObjectNewUploadResp) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectNewUploadResp) GetUploadID() string {
	if x != nil {
		return x.UploadID
	}
	return ""
}

type ObjectUploadPartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"key"
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"key"`
	// @inject_tag: json:"user_id"
	UserID string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"user_id"`
	// @inject_tag: json:"upload_id"
	UploadID string `protobuf:"bytes,3,opt,name=UploadID,proto3" json:"upload_id"`
	// @inject_tag: json:"body"
	Body string `protobuf:"bytes,4,opt,name=Body,proto3" json:"body"`
}

func (x *ObjectUploadPartReq) Reset() {
	*x = ObjectUploadPartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectUploadPartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectUploadPartReq) ProtoMessage() {}

func (x *ObjectUploadPartReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectUploadPartReq.ProtoReflect.Descriptor instead.
func (*ObjectUploadPartReq) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectUploadPartReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectUploadPartReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ObjectUploadPartReq) GetUploadID() string {
	if x != nil {
		return x.UploadID
	}
	return ""
}

func (x *ObjectUploadPartReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ObjectCompleteUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"user_id"
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"user_id"`
	// @inject_tag: json:"upload_id"
	UploadID string `protobuf:"bytes,2,opt,name=UploadID,proto3" json:"upload_id"`
}

func (x *ObjectCompleteUploadReq) Reset() {
	*x = ObjectCompleteUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectCompleteUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectCompleteUploadReq) ProtoMessage() {}

func (x *ObjectCompleteUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectCompleteUploadReq.ProtoReflect.Descriptor instead.
func (*ObjectCompleteUploadReq) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{8}
}

func (x *ObjectCompleteUploadReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ObjectCompleteUploadReq) GetUploadID() string {
	if x != nil {
		return x.UploadID
	}
	return ""
}

type ObjectAbortUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"upload_id"
	UploadID string `protobuf:"bytes,1,opt,name=UploadID,proto3" json:"upload_id"`
}

func (x *ObjectAbortUploadReq) Reset() {
	*x = ObjectAbortUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_metadata_api_src_object_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectAbortUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectAbortUploadReq) ProtoMessage() {}

func (x *ObjectAbortUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_metadata_api_src_object_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectAbortUploadReq.ProtoReflect.Descriptor instead.
func (*ObjectAbortUploadReq) Descriptor() ([]byte, []int) {
	return file_services_metadata_api_src_object_proto_rawDescGZIP(), []int{9}
}

func (x *ObjectAbortUploadReq) GetUploadID() string {
	if x != nil {
		return x.UploadID
	}
	return ""
}

var File_services_metadata_api_src_object_proto protoreflect.FileDescriptor

var file_services_metadata_api_src_object_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x12, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x72, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x32, 0x0a, 0x07, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x12, 0x27, 0x0a, 0x08, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x08, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a,
	0x0f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x22, 0x3e, 0x0a, 0x12, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x22, 0x31, 0x0a, 0x13, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x44, 0x22, 0x6f, 0x0a, 0x13, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x42, 0x6f, 0x64, 0x79, 0x22, 0x4d, 0x0a, 0x17, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x14, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x62, 0x6f,
	0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x44, 0x32, 0xf4, 0x02, 0x0a, 0x0d, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x14, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x29, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x09, 0x4e,
	0x65, 0x77, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x65,
	0x77, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x39,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x09,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x41, 0x62, 0x6f,
	0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x2d, 0x76,
	0x61, 0x72, 0x6d, 0x61, 0x7a, 0x79, 0x61, 0x72, 0x2f, 0x61, 0x72, 0x76, 0x61, 0x6e, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_services_metadata_api_src_object_proto_rawDescOnce sync.Once
	file_services_metadata_api_src_object_proto_rawDescData = file_services_metadata_api_src_object_proto_rawDesc
)

func file_services_metadata_api_src_object_proto_rawDescGZIP() []byte {
	file_services_metadata_api_src_object_proto_rawDescOnce.Do(func() {
		file_services_metadata_api_src_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_metadata_api_src_object_proto_rawDescData)
	})
	return file_services_metadata_api_src_object_proto_rawDescData
}

var file_services_metadata_api_src_object_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_services_metadata_api_src_object_proto_goTypes = []interface{}{
	(*Object)(nil),                  // 0: api.Object
	(*Objects)(nil),                 // 1: api.Objects
	(*ObjectListReq)(nil),           // 2: api.ObjectListReq
	(*ObjectReturnReq)(nil),         // 3: api.ObjectReturnReq
	(*ObjectDeleteReq)(nil),         // 4: api.ObjectDeleteReq
	(*ObjectNewUploadReq)(nil),      // 5: api.ObjectNewUploadReq
	(*ObjectNewUploadResp)(nil),     // 6: api.ObjectNewUploadResp
	(*ObjectUploadPartReq)(nil),     // 7: api.ObjectUploadPartReq
	(*ObjectCompleteUploadReq)(nil), // 8: api.ObjectCompleteUploadReq
	(*ObjectAbortUploadReq)(nil),    // 9: api.ObjectAbortUploadReq
	(*api.Void)(nil),                // 10: api.Void
}
var file_services_metadata_api_src_object_proto_depIdxs = []int32{
	0,  // 0: api.Objects.Elements:type_name -> api.Object
	2,  // 1: api.ObjectService.List:input_type -> api.ObjectListReq
	3,  // 2: api.ObjectService.Return:input_type -> api.ObjectReturnReq
	4,  // 3: api.ObjectService.Delete:input_type -> api.ObjectDeleteReq
	5,  // 4: api.ObjectService.NewUpload:input_type -> api.ObjectNewUploadReq
	7,  // 5: api.ObjectService.UploadPart:input_type -> api.ObjectUploadPartReq
	8,  // 6: api.ObjectService.CompleteUpload:input_type -> api.ObjectCompleteUploadReq
	9,  // 7: api.ObjectService.AbortUpload:input_type -> api.ObjectAbortUploadReq
	1,  // 8: api.ObjectService.List:output_type -> api.Objects
	0,  // 9: api.ObjectService.Return:output_type -> api.Object
	10, // 10: api.ObjectService.Delete:output_type -> api.Void
	6,  // 11: api.ObjectService.NewUpload:output_type -> api.ObjectNewUploadResp
	10, // 12: api.ObjectService.UploadPart:output_type -> api.Void
	10, // 13: api.ObjectService.CompleteUpload:output_type -> api.Void
	10, // 14: api.ObjectService.AbortUpload:output_type -> api.Void
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_services_metadata_api_src_object_proto_init() }
func file_services_metadata_api_src_object_proto_init() {
	if File_services_metadata_api_src_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_metadata_api_src_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Objects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectReturnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectNewUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectNewUploadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectUploadPartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectCompleteUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_metadata_api_src_object_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectAbortUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_metadata_api_src_object_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_metadata_api_src_object_proto_goTypes,
		DependencyIndexes: file_services_metadata_api_src_object_proto_depIdxs,
		MessageInfos:      file_services_metadata_api_src_object_proto_msgTypes,
	}.Build()
	File_services_metadata_api_src_object_proto = out.File
	file_services_metadata_api_src_object_proto_rawDesc = nil
	file_services_metadata_api_src_object_proto_goTypes = nil
	file_services_metadata_api_src_object_proto_depIdxs = nil
}
