// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: services/metadata/api/src/quota.proto

package api

import (
	context "context"
	api "github.com/h-varmazyar/arvanStorage/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuotaServiceClient is the client API for QuotaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuotaServiceClient interface {
	Remaining(ctx context.Context, in *QuotaRemainingReq, opts ...grpc.CallOption) (*QuotaRemainingResp, error)
	RequestLimit(ctx context.Context, in *QuotaRequestLimitReq, opts ...grpc.CallOption) (*QuotaRequestLimitResp, error)
	UpdateUsedVolume(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*api.Void, error)
}

type quotaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotaServiceClient(cc grpc.ClientConnInterface) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) Remaining(ctx context.Context, in *QuotaRemainingReq, opts ...grpc.CallOption) (*QuotaRemainingResp, error) {
	out := new(QuotaRemainingResp)
	err := c.cc.Invoke(ctx, "/api.QuotaService/Remaining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) RequestLimit(ctx context.Context, in *QuotaRequestLimitReq, opts ...grpc.CallOption) (*QuotaRequestLimitResp, error) {
	out := new(QuotaRequestLimitResp)
	err := c.cc.Invoke(ctx, "/api.QuotaService/RequestLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) UpdateUsedVolume(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*api.Void, error) {
	out := new(api.Void)
	err := c.cc.Invoke(ctx, "/api.QuotaService/UpdateUsedVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotaServiceServer is the server API for QuotaService service.
// All implementations should embed UnimplementedQuotaServiceServer
// for forward compatibility
type QuotaServiceServer interface {
	Remaining(context.Context, *QuotaRemainingReq) (*QuotaRemainingResp, error)
	RequestLimit(context.Context, *QuotaRequestLimitReq) (*QuotaRequestLimitResp, error)
	UpdateUsedVolume(context.Context, *Volume) (*api.Void, error)
}

// UnimplementedQuotaServiceServer should be embedded to have forward compatible implementations.
type UnimplementedQuotaServiceServer struct {
}

func (UnimplementedQuotaServiceServer) Remaining(context.Context, *QuotaRemainingReq) (*QuotaRemainingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remaining not implemented")
}
func (UnimplementedQuotaServiceServer) RequestLimit(context.Context, *QuotaRequestLimitReq) (*QuotaRequestLimitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestLimit not implemented")
}
func (UnimplementedQuotaServiceServer) UpdateUsedVolume(context.Context, *Volume) (*api.Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUsedVolume not implemented")
}

// UnsafeQuotaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotaServiceServer will
// result in compilation errors.
type UnsafeQuotaServiceServer interface {
	mustEmbedUnimplementedQuotaServiceServer()
}

func RegisterQuotaServiceServer(s grpc.ServiceRegistrar, srv QuotaServiceServer) {
	s.RegisterService(&QuotaService_ServiceDesc, srv)
}

func _QuotaService_Remaining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaRemainingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).Remaining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.QuotaService/Remaining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).Remaining(ctx, req.(*QuotaRemainingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_RequestLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotaRequestLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).RequestLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.QuotaService/RequestLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).RequestLimit(ctx, req.(*QuotaRequestLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_UpdateUsedVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Volume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).UpdateUsedVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.QuotaService/UpdateUsedVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).UpdateUsedVolume(ctx, req.(*Volume))
	}
	return interceptor(ctx, in, info, handler)
}

// QuotaService_ServiceDesc is the grpc.ServiceDesc for QuotaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuotaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Remaining",
			Handler:    _QuotaService_Remaining_Handler,
		},
		{
			MethodName: "RequestLimit",
			Handler:    _QuotaService_RequestLimit_Handler,
		},
		{
			MethodName: "UpdateUsedVolume",
			Handler:    _QuotaService_UpdateUsedVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/metadata/api/src/quota.proto",
}
